name: Project
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      opened
    branches:
      - main  

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout from repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
              
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: code-checkout from repo
              uses: actions/checkout@v4

            - name: Install dependencies required to run the project
              run: npm install

            - name: Build the project for my react application
              run: npm run build
              
            - name: Deploy the project
              run: |
               echo "Build successfull!!"
               echo "Deploying to ......"

