name: Project
on: push
jobs:
    test:
        runs-on: ubuntu-20.04
        steps:
            - name: code checkout from repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
              
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: code-checkout from repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Build the project
              run: npm run build
              
            - name: Deploy the project
              run: |
               echo "Build successfull!!"
               echo "Deploying to ......"

